"""create core tables

Revision ID: 0f7cc4c8eed8
Revises:
Create Date: 2026-05-30 19:50:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.mysql import DECIMAL

# revision identifiers, used by Alembic.
revision: str = "0f7cc4c8eed8"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("phone", sa.String(20), nullable=True),
        sa.Column("password_hash", sa.String(255), nullable=True),
        sa.Column("wechat_openid", sa.String(128), nullable=True),
        sa.Column("role", sa.String(20), nullable=False),
        sa.Column("parent_user_id", sa.String(36), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["parent_user_id"], ["users.id"], ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone"),
        sa.UniqueConstraint("wechat_openid"),
    )
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("user_id", sa.String(36), nullable=False),
        sa.Column("refresh_token", sa.String(512), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False)
    op.create_table(
        "user_ai_balance",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("user_id", sa.String(36), nullable=False),
        sa.Column("image_credits", sa.Integer(), nullable=False),
        sa.Column("text_credits", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "user_ai_usage",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("user_id", sa.String(36), nullable=False),
        sa.Column("action_type", sa.String(20), nullable=False),
        sa.Column("credits_used", DECIMAL(10, 4), nullable=False),
        sa.Column("api_cost", DECIMAL(10, 6), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_ai_usage_action_type"), "user_ai_usage", ["action_type"], unique=False)
    op.create_index(op.f("ix_user_ai_usage_created_at"), "user_ai_usage", ["created_at"], unique=False)
    op.create_index(op.f("ix_user_ai_usage_user_id"), "user_ai_usage", ["user_id"], unique=False)
    op.create_table(
        "recharge_orders",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("user_id", sa.String(36), nullable=False),
        sa.Column("order_no", sa.String(64), nullable=False),
        sa.Column("amount", DECIMAL(10, 2), nullable=False),
        sa.Column("payment_method", sa.String(20), nullable=True),
        sa.Column("status", sa.String(20), nullable=False),
        sa.Column("package_type", sa.String(20), nullable=False),
        sa.Column("image_credits", sa.Integer(), nullable=False),
        sa.Column("text_credits", sa.Integer(), nullable=False),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_no"),
    )
    op.create_index(op.f("ix_recharge_orders_user_id"), "recharge_orders", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recharge_orders_user_id"), table_name="recharge_orders")
    op.drop_table("recharge_orders")
    op.drop_index(op.f("ix_user_ai_usage_user_id"), table_name="user_ai_usage")
    op.drop_index(op.f("ix_user_ai_usage_created_at"), table_name="user_ai_usage")
    op.drop_index(op.f("ix_user_ai_usage_action_type"), table_name="user_ai_usage")
    op.drop_table("user_ai_usage")
    op.drop_table("user_ai_balance")
    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_table("users")
    # ### end Alembic commands ###
